# Generated by Django 2.2.15 on 2020-08-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200822_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user2tes',
            new_name='user2tesmmm',
        ),
    ]
