# Generated by Django 2.2.15 on 2020-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200822_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='newapp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
